name = "CoordinationGames"
uuid = "4bb2c6fa-c716-443c-bd78-f2a2f3c4e880"
authors = ["NoFishLikeIan <andreatitton96@gmail.com> and contributors"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
