name = "CooperativeGames"
uuid = "4bb2c6fa-c716-443c-bd78-f2a2f3c4e880"
authors = ["NoFishLikeIan <andreatitton96@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Combinatorics = "~1.0.2"
IterTools = "~1.3.0"
LightGraphs = "1.3"
Revise = "~3.1.14"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
